#!/usr/bin/python

import sys, os, re, plistlib, urllib2

base_path=""
if len(sys.argv) > 1:
	base_path=sys.argv[1]

result=[]
ignore=["Library", "Movies", "TV Shows", "Podcasts", "Books", "Music", "Voice Memos"]

plist = plistlib.readPlist("/Users/riegersn/Music/iTunes/iTunes Music Library.xml")
playlists=plist["Playlists"]
tracks=plist["Tracks"]

for pl in playlists:
	pname = pl["Name"]
	if pname not in ignore:

		file_name = pname + ".m3u"

		if os.path.isdir(base_path):
			file_name = os.path.join(base_path, file_name)

		fo = open(file_name, "wb")

		fo.write("# M3U Playlist generated by exportip.py (Shawn Rieger)\n")
		for tr in pl["Playlist Items"]:
			location=tracks[str(tr["Track ID"])]["Location"]
			if not location.endswith('.m4v'):
				location = re.sub(r'(^.*?Media/Music)', 'music', urllib2.unquote(location))
				fo.write(location.replace("/", "\\") + "\n")
		fo.close()
